const canvas=document.getElementById('canvas'),ctx=canvas.getContext('2d');let drawing=false,startX=0,startY=0,tool='brush',color='#4b45a9',size=8;let history=[],future=[];let currentStroke=null;
function resizeCanvas(){const old=document.createElement('canvas');old.width=canvas.width;old.height=canvas.height;if(canvas.width&&canvas.height)old.getContext('2d').drawImage(canvas,0,0);const r=canvas.getBoundingClientRect();canvas.width=Math.max(700,Math.floor(r.width));canvas.height=Math.max(420,Math.floor(r.width*.55));ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);if(old.width&&old.height)ctx.drawImage(old,0,0,old.width,old.height,0,0,canvas.width,canvas.height);}
function snapshot(){return canvas.toDataURL('image/png')}function restore(data){const img=new Image();img.onload=()=>{ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height)};img.src=data}
function pushHistory(){history.push(snapshot());if(history.length>30)history.shift();future=[]}
function point(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}
function prepare(){ctx.lineCap='round';ctx.lineJoin='round';ctx.lineWidth=size;ctx.strokeStyle=tool==='eraser'?'#fff':color}
function start(e){e.preventDefault();drawing=true;const p=point(e);startX=p.x;startY=p.y;prepare();currentStroke=snapshot();if(tool==='brush'||tool==='eraser'){ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+.1,p.y+.1);ctx.stroke()}}
function move(e){if(!drawing)return;e.preventDefault();const p=point(e);prepare();if(tool==='brush'||tool==='eraser'){ctx.lineTo(p.x,p.y);ctx.stroke();ctx.beginPath();ctx.moveTo(p.x,p.y)}else{restore(currentStroke);ctx.beginPath();if(tool==='line'){ctx.moveTo(startX,startY);ctx.lineTo(p.x,p.y)}else{const rx=Math.abs(p.x-startX),ry=Math.abs(p.y-startY),r=Math.max(rx,ry);ctx.arc(startX,startY,r,0,Math.PI*2)}ctx.stroke()}}
function end(){if(!drawing)return;drawing=false;ctx.beginPath();history.push(currentStroke);if(history.length>30)history.shift();future=[];document.getElementById('canvasTip').style.display='none';document.getElementById('points').textContent=Number(document.getElementById('points').textContent)+1}
canvas.addEventListener('mousedown',start);canvas.addEventListener('mousemove',move);window.addEventListener('mouseup',end);canvas.addEventListener('touchstart',start,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});canvas.addEventListener('touchend',end);
document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tool').forEach(x=>x.classList.remove('active'));b.classList.add('active');tool=b.dataset.tool});document.querySelectorAll('.swatch').forEach(b=>b.onclick=()=>{color=b.dataset.color;document.getElementById('color').value=color;tool='brush';document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x.dataset.tool==='brush'))});document.getElementById('color').oninput=e=>{color=e.target.value;tool='brush';document.querySelectorAll('.tool').forEach(x=>x.classList.toggle('active',x.dataset.tool==='brush'))};document.getElementById('size').oninput=e=>{size=+e.target.value;document.getElementById('sizeValue').textContent=size+' px'};
document.getElementById('undo').onclick=()=>{if(!history.length)return;future.push(snapshot());restore(history.pop())};document.getElementById('redo').onclick=()=>{if(!future.length)return;history.push(snapshot());restore(future.pop())};document.getElementById('clear').onclick=()=>{pushHistory();ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);document.getElementById('canvasTip').style.display='block'};document.getElementById('save').onclick=()=>{const a=document.createElement('a');a.download='my-ict-masterpiece.png';a.href=canvas.toDataURL('image/png');a.click()};
const challenges=['Draw a happy sun, then add three clouds!','Draw your favourite animal using at least three colours!','Create a robot with two buttons and a funny face!','Draw a rainbow and a small house underneath it!','Make a garden with flowers, leaves and a butterfly!'];document.getElementById('newChallenge').onclick=()=>{document.getElementById('challengeText').textContent=challenges[Math.floor(Math.random()*challenges.length)]};
function init(){canvas.width=900;canvas.height=500;ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height)}init();
